<?php
$parameters = array(
    'site_url' => '##site_url##',
    'cache_path' => '##cache_path##',
    'log_path' => '##log_path##',
    'install_source' => 'Mautic',
    'db_driver' => 'pdo_mysql',
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_name' => '##db_name##',
    'db_user' => '##db_user##',
    'db_password' => '##db_password##',
    'db_path' => null,
    'mailer_from_name' => '55hubs',
    'mailer_from_email' => 'admin@55hubs.ch',
    'mailer_transport' => 'mail',
    'mailer_host' => null,
    'mailer_port' => null,
    'mailer_user' => 'root',
    'mailer_password' => 'root',
    'mailer_encryption' => null,
    'mailer_auth_mode' => null,
    'mailer_spool_type' => 'memory',
    'mailer_spool_path' => '##mailer_spool_path##',
    'secret_key' => '##secret_key##',
    'default_timezone' => 'Europe/Zurich',
    'date_format_full' => 'j F, Y G:i',
    'date_format_short' => 'd M Y',
    'date_format_dateonly' => 'd M Y',
    'date_format_timeonly' => 'G:i',
    'ip_lookup_service' => 'maxmind_download',
    'do_not_track_ips' => array(
        "213.221.250.50"
    ),
);